# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Main CI

on:
  push:
    branches: 
    - main
    - develop
  pull_request:
    branches: 
    - main
    - develop

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        
    steps:
      
      - name: Copy repository
        uses: actions/checkout@v2
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install npm dependencies
        run: yarn install
      
      - name: Lint code
        run: yarn lint
      
      - name: Run tests and coverage
        run: yarn test:cov
      
      - name: Run end to end test
        run: yarn test:e2e
        
        
      - name: Run build
        run: yarn build
